version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: freelance_manager-postgres
    restart: always
    environment:
      POSTGRES_USER: es2_user
      POSTGRES_PASSWORD: ABC@123
      POSTGRES_DB: freelancemanager_db_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database:/database

  pgadmin:
    image: dpage/pgadmin4
    container_name: freelance_manager-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@freelancer.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local